In [1]:
import warnings
warnings.filterwarnings("ignore")
from pandas import Series, DataFrame
import pandas as pd
import pandas_datareader.data as web
import numpy as np
from fbprophet import Prophet
from datetime import datetime
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import platform
from matplotlib import font_manager, rc
plt. rcParams['axes.unicode_minus'] = False

if platform.system() == 'Darwin' :
    rc('font', family = 'AppleGothic')
elif platform.system() == 'Windows' :
    path = 'C:/Windows/Fonts/NotoSansCJKkr-Black.otf'
    font_name = font_manager.FontProperties(fname = path).get_name()
    rc('font', family = font_name)
else:
    print('Unknown system... sorry~~~~')

ModuleNotFoundError: No module named 'fbprophet'

In [2]:
bike_sharing = pd.read_csv("C:/practice/data/train.csv", encoding  = 'utf-8')
bike_sharing.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1

In [45]:
bike_sharing[0]

KeyError: 0

In [48]:
type(bike_sharing['datetime'])

pandas.core.series.Series

In [ ]:
plt.figure(figsize = (10, 10))
plt.scatter(  bike_sharing['datetime'], bike_sharing['count'],  s = 10)
plt.xlabel('datetime')
plt.ylabel('count')
plt.grid()
plt.show()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
5,2011-01-01 05:00:00,1,0,0,2,9.84,12.880,75,6.0032,0,1,1
6,2011-01-01 06:00:00,1,0,0,1,9.02,13.635,80,0.0000,2,0,2
7,2011-01-01 07:00:00,1,0,0,1,8.20,12.880,86,0.0000,1,2,3
8,2011-01-01 08:00:00,1,0,0,1,9.84,14.395,75,0.0000,1,7,8
9,2011-01-01 09:00:00,1,0,0,1,13.12,17.425,76,0.0000,8,6,14
10,2011-01-01 10:00:00,1,0,0,1,15.58,19.695,76,16.9979,12,24,36
11,2011-01-01 11:00:00,1,0,0,1,14.76,16.665,81,19.0012,26,30,56
12,2011-01-01 12:00:00,1,0,0,1,17.22,21.210,77,19.0012,29,55,84
13,2011-01-01 13:00:00,1,0,0,2,18.86,22.725,72,19.9995,47,47,94
14,2011-01-01 14:00:00,1,0,0,2,18.86,22.725,72,19.0012,35,71,106
15,2011-01-01 15:00:00,1,0,0,2,18.04,21.970,77,19.9995,40,70,110
16,2011-01-01 16:00:00,1,0,0,2,17.22,21.210,82,19.9995,41,52,93
17,2011-01-01 17:00:00,1,0,0,2,18.04,21.970,82,19.0012,15,52,67
18,2011-01-01 18:00:00,1,0,0,3,17.22,21.210,88,16.9979,9,26,35
19,2011-01-01 19:00:00,1,0,0,3,17.22,21.210,88,16.9979,6,31,37
20,2011-01-01 20:00:00,1,0,0,2,16.40,20.455,87,16.9979,11,25,36
21,2011-01-01 21:00:00,1,0,0,2,16.40,20.455,87,12.9980,3,31,34
22,2011-01-01 22:00:00,1,0,0,2,16.40,20.455,94,15.0013,11,17,28
23,2011-01-01 23:00:00,1,0,0,2,18.86,22.725,88,19.9995,15,24,39
24,2011-01-02 00:00:00,1,0,0,2,18.86,22.725,88,19.9995,4,13,17
25,2011-01-02 01:00:00,1,0,0,2,18.04,21.970,94,16.9979,1,16,17
26,2011-01-02 02:00:00,1,0,0,2,17.22,21.210,100,19.0012,1,8,9
27,2011-01-02 03:00:00,1,0,0,2,18.86,22.725,94,12.9980,2,4,6
28,2011-01-02 04:00:00,1,0,0,2,18.86,22.725,94,12.9980,2,1,3
29,2011-01-02 06:00:00,1,0,0,3,17.22,21.210,77,19.9995,0,2,2
30,2011-01-02 07:00:00,1,0,0,2,16.40,20.455,76,12.9980,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10856,2012-12-18 18:00:00,4,0,1,1,15.58,19.695,46,22.0028,13,512,525
10857,2012-12-18 19:00:00,4,0,1,1,15.58,19.695,46,26.0027,19,334,353
10858,2012-12-18 20:00:00,4,0,1,1,14.76,16.665,50,16.9979,4,264,268
10859,2012-12-18 21:00:00,4,0,1,1,14.76,17.425,50,15.0013,9,159,168
10860,2012-12-18 22:00:00,4,0,1,1,13.94,16.665,49,0.0000,5,127,132
10861,2012-12-18 23:00:00,4,0,1,1,13.94,17.425,49,6.0032,1,80,81
10862,2012-12-19 00:00:00,4,0,1,1,12.30,15.910,61,0.0000,6,35,41
10863,2012-12-19 01:00:00,4,0,1,1,12.30,15.910,65,6.0032,1,14,15
10864,2012-12-19 02:00:00,4,0,1,1,11.48,15.150,65,6.0032,1,2,3
10865,2012-12-19 03:00:00,4,0,1,1,10.66,13.635,75,8.9981,0,5,5
10866,2012-12-19 04:00:00,4,0,1,1,9.84,12.120,75,8.9981,1,6,7
10867,2012-12-19 05:00:00,4,0,1,1,10.66,14.395,75,6.0032,2,29,31
10868,2012-12-19 06:00:00,4,0,1,1,9.84,12.880,75,6.0032,3,109,112
10869,2012-12-19 07:00:00,4,0,1,1,10.66,13.635,75,8.9981,3,360,363
10870,2012-12-19 08:00:00,4,0,1,1,9.84,12.880,87,7.0015,13,665,678
10871,2012-12-19 09:00:00,4,0,1,1,11.48,14.395,75,7.0015,8,309,317
10872,2012-12-19 10:00:00,4,0,1,1,13.12,16.665,70,7.0015,17,147,164
10873,2012-12-19 11:00:00,4,0,1,1,16.40,20.455,54,15.0013,31,169,200
10874,2012-12-19 12:00:00,4,0,1,1,16.40,20.455,54,19.0012,33,203,236
10875,2012-12-19 13:00:00,4,0,1,1,17.22,21.210,50,12.9980,30,183,213
10876,2012-12-19 14:00:00,4,0,1,1,17.22,21.210,50,12.9980,33,185,218
10877,2012-12-19 15:00:00,4,0,1,1,17.22,21.210,50,19.0012,28,209,237
10878,2012-12-19 16:00:00,4,0,1,1,17.22,21.210,50,23.9994,37,297,334
10879,2012-12-19 17:00:00,4,0,1,1,16.40,20.455,50,26.0027,26,536,562
10880,2012-12-19 18:00:00,4,0,1,1,15.58,19.695,50,23.9994,23,546,569
10881,2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336
10882,2012-12-19 20:00:00,4,0,1,1,14.76,17.425,57,15.0013,10,231,241
10883,2012-12-19 21:00:00,4,0,1,1,13.94,15.910,61,15.0013,4,164,168
10884,2012-12-19 22:00:00,4,0,1,1,13.94,17.425,61,6.0032,12,117,129
10885,2012-12-19 23:00:00,4,0,1,1,13.12,16.665,66,8.9981,4,84,88